### ISSUE TITLE
Suggestion: configurable patterns

### ISSUE THREAD

**Issue by tdtm** [k00ni/todolo#1]
I was looking for something like that recently, and one made in PHP is even better. Well done!

Suggestion: rather than hardcoding `fixme`/`todo`/`@todo`, make it possible to provide custom patterns (or disable those if prefered). Those you've already got could be default, but users could add more as needed, eg a pattern for `hack`, or a `FIXME` that's case sensitive or insensitive, etc.

If that's not something you've always got plans for, I'd consider looking into submitting a PR for that.

**Comment by k00ni** [comment]
Hi @tdtm, I am glad to see interest in this little project of mine.

I find your idea tempting providing additional (or all) patterns via configuration. But I am also torn, because it touches an either-or-decision. 

On one hand I would like to keep the configuration file plain and simple. Some on/off parts, some lists, that's it. No logic or even parts which control internals. Users don't have to maintain their detailed configuration and can rely on the core, which have their backs.

On the other hand your suggestion allows more flexible ways to use this tool. You mentioned there could be a default stack of patterns and a user stack, provided by the configuration file. How could that look? (key => value maybe) Can you post an example please?

Small side note: More standardized TODO annotations would be great (e.g. only use TODO and not HACK etc. anymore). Similar to coding standards for PHP, like PSR-2. That said, I am looking forward to your feedback.

**Comment by tdtm** [comment]
I understand the desire for simplicity!

Looking at the existing source, methods `extractSingleLineAtTODOs()`, `extractSingleLineFIXMEs()` and `extractSingleLineTODOs()` are nearly the same. So to keep it simple, I'd have a single method called 

Briefly, my suggestion would be:
- Create constants for each of the patterns, eg `TodoFinder::PATTERN_FIXME = '/[\/\/|\*]\s+FIXME[:]*\s*(.*)/mi'`
- Have a configuration key named something like `patterns`. Its default value (if omitted) would be `[TodoFinder::PATTERN_FIXME, TodoFinder::PATTERN_TODO, TodoFinder::PATTERN_AT_TODO]`.
- People can override the default by setting only one some of the defaults, or providing their own regex patterns.
- Add a instance property in TodoFinder: `protected array $patterns` that gets set in the constructor from the config value.
- Replace the three method above with a single method that has a `string $pattern` parameter; in `extractAllTodos()`, iterate on `$this->pattern` instead of having each individual call.

The above approach would keep the simplicity (no mandatory configuration change: if you keep the same config, you get the same result) but would provide a bit more options.

**Comment by k00ni** [comment]
Hi @tdtm, that sounds good. Moving patterns to constant is a little bit odd for me, but it can make sense, surely. To be honest, the current architecture is not fixed, so there could be deep changes. And because this library only provides an API via console + config file, internal changes can be done more freely. 

I am open for a PR, if you want. Lets discuss details there.

**Comment by tdtm** [comment]
Sounds good!
